### ISSUE TITLE
Crease should be order independent

### ISSUE THREAD

**Issue by notmahi** [alam-shahul/Polygami#1]
Right now, the crease start and endpoints matter when we check whether a crease exists or add a new crease. I suggest that the creases be endpoint-order-agnostic.

**Comment by lahuang4** [comment]
Do you have a suggestion for how to make these more order-agnostic? The start and end points are effectively equivalent right now despite the names; we check each of them in the same way.

**Comment by lahuang4** [comment]
Shahul changed this in the crease class in 739f327; now they have an array of 2 endpoints.
