### ISSUE TITLE
Issue with MV coloring in smaller grids

### ISSUE THREAD

**Issue by lahuang4** [alam-shahul/Polygami#11]
In 4x4 and smaller grids, the extended coloring is correct but switching to the MV coloring creates blue solid lines (which are supposed to be dashed).

Extended coloring:
![image](https://cloud.githubusercontent.com/assets/5505889/25607109/0dc625de-2ee3-11e7-86be-c0198f6136df.png)

MV coloring:
![image](https://cloud.githubusercontent.com/assets/5505889/25607155/49ced5e4-2ee3-11e7-9920-7d31305b5a03.png)

**Comment by alam-shahul** [comment]
I think it's resolved?
