### ISSUE TITLE
List of Corners returned by computeCorners keyed incorrectly

### ISSUE THREAD

**Issue by alam-shahul** [alam-shahul/Polygami#5]
The dictionary of Corners in the Grid object that is modified by computeCorners is supposed to be keyed by Point.toString(corner.tip.x, corner.tip.y) for each Corner, but it seems to be off by one in many cases.

**Comment by notmahi** [comment]
The dictionary on corners are keyed by their bottom-left point, not the tip. You can find the tip inside the associated Corner object.
